config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'dashboard#index'
  end
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :series
  resources :categories
  resources :games
  resources :levels
  resources :resources
  resources :skips
  resources :tricks
  resources :guides
  resources :game_tricks

  namespace :admin do
    resources :series
    resources :categories
    resources :games
    resources :levels
    resources :resources
    resources :skips
    resources :tricks
    resources :guides
    resources :game_tricks
  end
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id           :bigint           not null, primary key
#  name         :string
#  overview     :text
#  platform     :string
#  release_date :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  series_id    :bigint           not null
#
# Indexes
#
#  index_games_on_series_id  (series_id)
#
# Foreign Keys
#
#  fk_rails_...  (series_id => series.id)
#
class Game < ApplicationRecord
  belongs_to :series
  has_many :categories
  has_many :levels
  has_many :guides
  has_many :skips
  has_many :game_tricks
  has_many :tricks, through: :game_tricks
  accepts_nested_attributes_for :game_tricks, allow_destroy: true
  has_rich_text :overview

  validates :name, presence: true
  validates :platform, presence: true
  validates :release_date, presence: true
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < Admin::BaseController
  def index
    @games = Game.all
  end

  def trick_index
    @tricks = Trick.all
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to [:admin, @game]
    else
      render :edit
    end
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to [:admin, @game]
    else
      render :new
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to admin_games_path
  end

  def show
    @game = Game.find(params[:id])
  end

  private

  def game_params
    params.require(:game).permit(:name, :platform, :release_date, :series_id, :overview, game_tricks_attributes: [:trick_id, :id, :_destroy])
  end
end

app/controllers/games_controller.rb
# The public view controller for games. Doesn't require things like CRUD, just viewing.
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  private

  def game_params
    params.require(:game).permit(:name, :platform, :release_date, :series_id, :overview, game_tricks_attributes: [:trick_id])
  end
end

app/views/admin/games/_form.html.erb
<%= simple_form_for [:admin, game] do |f| %>
  <%= f.input :name %>
  <%= f.input :platform %>
  <div class="field">
    <%= f.label :overview %>
    <%= f.rich_text_area :overview %>
  </div>
  <%= f.input :release_date %>
  <%= f.association :series %>
  <div>
    <%= f.simple_fields_for :game_tricks do |game_trick| %>
      <%= render 'game_trick_fields', f: game_trick %>
    <% end %>
  </div>
  <div><%= link_to_add_association 'Add Trick', f, :game_tricks %></div>
  <%= f.submit %>
<% end %>

app/views/admin/games/_game_trick_fields.html.erb
<div class="nested-fields">
  <%= f.association :trick, collection: Trick.all %>
  <%= link_to_remove_association 'Remove Trick', f %>
</div>

app/views/admin/games/edit.html.erb
<h1>Editing Game #<%= @game.id %></h1>
<%= render 'form', game: @game %>

app/views/admin/games/index.html.erb
<h1>Games</h1>
<ul>
  <% @games.each do |game| %>
    <li><%= link_to game.name, [:admin, game] %></li>
  <% end %>
</ul>
<%= link_to 'New Game', new_admin_game_path %>

app/views/admin/games/new.html.erb
<h1>New Game</h1>
<%= render 'form', game: @game %>

app/views/admin/games/show.html.erb
<h1><%= @game.name %></h1>
<ul>
  <li><strong>Series:</strong> <%= @game.series.name %></li>
  <li><strong>Release Date:</strong> <%= @game.release_date %></li>
  <li><strong>Platform:</strong> <%= @game.platform %></li>
  <li><strong>Overview:</strong></li>
  <li><%= @game.overview %></li>
</ul>
<strong>Associated Categories:</strong>
<ul>
  <% @game.categories.each do |category| %>
    <li><%= link_to category.name, [:admin, category] %></li>
  <% end %>
</ul>
<strong>Associated Tricks:</strong>
<ul>
    <% @game.tricks.each do |trick| %>
      <li><%= link_to trick.name, [:admin, trick] %></li>
    <% end %>
</ul>
<ul>
  <li><%= link_to "Edit", edit_admin_game_path(@game) %></li>
  <li><%= link_to "Destroy", admin_game_url(@game),
    method: :delete,
    data: { confirm: "Are you sure?" } %></li>
</ul>