config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'dashboard#index'
  end
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :series
  resources :categories
  resources :games
  resources :levels
  resources :resources
  resources :skips
  resources :tricks
  resources :guides
  resources :game_tricks

  namespace :admin do
    resources :series
    resources :categories
    resources :games
    resources :levels
    resources :resources
    resources :skips
    resources :tricks
    resources :guides
    resources :game_tricks
  end
end

app/models/guide.rb
# == Schema Information
#
# Table name: guides
#
#  id           :bigint           not null, primary key
#  content      :text
#  creator      :string
#  game_version :string
#  name         :string
#  revision     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  category_id  :bigint           not null
#  game_id      :bigint           not null
#
# Indexes
#
#  index_guides_on_category_id  (category_id)
#  index_guides_on_game_id      (game_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (game_id => games.id)
#
class Guide < ApplicationRecord
  belongs_to :game
  belongs_to :category
  has_rich_text :content

  validates :name, presence: true
  validates :revision, presence: true
  validates :content, presence: true
end

app/controllers/admin/guides_controller.rb
class Admin::GuidesController < Admin::BaseController
  def index
    @guides = Guide.all.includes(:category)
    @categories = Category.all
    @games = Game.all
  end

  def new
    @guide = Guide.new
  end

  def edit
    @guide = Guide.find(params[:id])
  end

  def update
    @guide = Guide.find(params[:id])

    if @guide.update(guide_params)
      redirect_to [:admin, @guide]
    else
      render :edit
    end
  end

  def create
    @guide = Guide.new(guide_params)
    if @guide.save
      redirect_to [:admin, @guide]
    else
      render :new
    end
  end

  def destroy
    @guide = Guide.find(params[:id])
    @guide.destroy

    redirect_to admin_guides_path
  end

  def show
    @guide = Guide.find(params[:id])
  end

  private

  def guide_params
    params.require(:guide).permit(:name, :revision, :category_id, :game_id, :content, :creator, :game_version)
  end

  def category_params
    params.require(:category).permit(:name, :overview, :platform, :rules, :game_id)
  end

  def game_params
    params.require(:game).permit(:name, :platform, :release_date, :series_id, :overview, game_tricks_attributes: [:trick_id])
  end
end

app/controllers/guides_controller.rb
# The public view controller for guides. Doesn't require things like CRUD, just viewing.
class GuidesController < ApplicationController
  # The duplicated code here (from the game & category controllers) is needed to separate the guides by
  # game & category on the guide index page.
  def index
    @guides = Guide.all.includes(:category)
    @categories = Category.all
    @games = Game.all
  end

  def show
    @guide = Guide.find(params[:id])
  end

  private

  def guide_params
    params.require(:guide).permit(:name, :revision, :category_id, :game_id, :content, :creator, :game_version)
  end

  def category_params
    params.require(:category).permit(:name, :overview, :platform, :rules, :game_id)
  end

  def game_params
    params.require(:game).permit(:name, :platform, :release_date, :series_id, :overview, game_tricks_attributes: [:trick_id])
  end
end

app/views/admin/guides/_form.html.erb
<%= simple_form_for [:admin, guide] do |f| %>
  <%= f.input :name %>
  <%= f.input :game_version %>
  <%= f.input :revision %>
  <%= f.input :creator %>
  <%= f.association :game %>
  <%= f.association :category %>
  <div class="field">
    <%= f.label :content %>
    <%= f.rich_text_area :content %>
  </div>
  <%= f.submit %>
<% end %>

app/views/admin/guides/edit.html.erb
<h1>Editing Guide #<%= @guide.id %></h1>
<%= render 'form', guide: @guide %>

app/views/admin/guides/index.html.erb
<h1>Guides</h1>
<% @games.each do |game|%>
  <h3> <%= game.name %> </h3>
    <% game.categories.each do |category| %>
      <div>
        <h5><%= category.name %></h5>
          <ul>
            <% category.guides.each do |guide| %>
              <li><%= link_to guide.name, [:admin, guide] %></li>
            <% end %>
          </ul>
      </div>
    <% end %>
<% end %>
<%= link_to 'New Guide', new_admin_guide_path %>

app/views/admin/guides/new.html.erb
<h1>New Guide</h1>
<%= render 'form', guide: @guide %>

app/views/admin/guides/show.html.erb
<h1><%= @guide.name %></h1>
<ul>
  <li><strong>Game:</strong> <%= @guide.game.name %></li>
  <li><strong>Category:</strong> <%= @guide.category.name %></li>
  <li><strong>Game Version:</strong> <%= @guide.game_version %></li>
  <li><strong>Revision:</strong> <%= @guide.revision %></li>
  <li><strong>Creator:</strong> <%= @guide.creator %></li>
  <li><strong>Guide:</strong></li>
  <li><%= @guide.content %> </li>
</ul>
<ul>
  <li><%= link_to "Edit", edit_admin_guide_path(@guide) %></li>
  <li><%= link_to "Destroy", admin_guide_url(@guide),
    method: :delete,
    data: { confirm: "Are you sure?" } %></li>
</ul>