config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'dashboard#index'
  end
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :series
  resources :categories
  resources :games
  resources :levels
  resources :resources
  resources :skips
  resources :tricks
  resources :guides
  resources :game_tricks

  namespace :admin do
    resources :series
    resources :categories
    resources :games
    resources :levels
    resources :resources
    resources :skips
    resources :tricks
    resources :guides
    resources :game_tricks
  end
end

app/models/trick.rb
# == Schema Information
#
# Table name: tricks
#
#  id           :bigint           not null, primary key
#  description  :text
#  discoverer   :string
#  game_version :string
#  name         :string
#  platform     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Trick < ApplicationRecord
  has_many :games, through: :game_tricks
  has_rich_text :description

  validates :name, presence: true
  validates :discoverer, presence: true
  validates :description, presence: true
end

app/controllers/admin/tricks_controller.rb
class Admin::TricksController < Admin::BaseController
  def index
    @tricks = Trick.all
  end

  def new
    @trick = Trick.new
  end

  def edit
    @trick = Trick.find(params[:id])
  end

  def update
    @trick = Trick.find(params[:id])

    if @trick.update(trick_params)
      redirect_to [:admin, @trick]
    else
      render :edit
    end
  end

  def create
    @trick = Trick.new(trick_params)
    if @trick.save
      redirect_to [:admin, @trick]
    else
      render :new
    end
  end

  def destroy
    @trick = Trick.find(params[:id])
    @trick.destroy

    redirect_to admin_tricks_path
  end

  def show
    @trick = Trick.find(params[:id])
  end

  private

  def trick_params
    params.require(:trick).permit(:name, :discoverer, :description, :game_version, :platform, game_tricks_attributes: [:trick_id])
  end
end

app/controllers/tricks_controller.rb
# The public view controller for tricks. Doesn't require things like CRUD, just viewing.
class TricksController < ApplicationController
  def index
    @tricks = Trick.all
  end

  def show
    @trick = Trick.find(params[:id])
  end

  private

  def trick_params
    params.require(:trick).permit(:name, :discoverer, :description, :game_version, :platform, game_tricks_attributes: [:trick_id])
  end
end

app/views/admin/tricks/_form.html.erb
<%= simple_form_for [:admin, trick] do |f| %>
  <%= f.input :name %>
  <%= f.input :game_version %>
  <%= f.input :discoverer %>
  <%= f.input :platform %>
  <div class="field">
    <%= f.label :description %>
    <%= f.rich_text_area :description %>
  </div>
  <%= f.submit %>
<% end %>

app/views/admin/tricks/edit.html.erb
<h1>Editing Trick #<%= @trick.id %></h1>
<%= render 'form', trick: @trick %>

app/views/admin/tricks/index.html.erb
<h1>Tricks</h1>
<ul>
  <% @tricks.each do |trick| %>
    <li><%= link_to trick.name, [:admin, trick] %></li>
  <% end %>
</ul>
<%= link_to 'New Trick', new_admin_trick_path %>

app/views/admin/tricks/new.html.erb
<h1>New Trick</h1>
<%= render 'form', trick: @trick %>

app/views/admin/tricks/show.html.erb
<h1><%= @trick.name %></h1>
<ul>
  <li><strong>Discoverer:</strong> <%= @trick.discoverer %></li>
  <li><strong>Game Version:</strong> <%= @trick.game_version %></li>
  <li><strong>Platform:</strong> <%= @trick.platform %></li>
  <li><strong>Description:</strong></li>
  <li><%= @trick.description %></li>
</ul>
<ul>
  <li><%= link_to "Edit", edit_admin_trick_path(@trick) %></li>
  <li><%= link_to "Destroy", admin_trick_url(@trick),
    method: :delete,
    data: { confirm: "Are you sure?" } %></li>
</ul>