config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'dashboard#index'
  end
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :series
  resources :categories
  resources :games
  resources :levels
  resources :resources
  resources :skips
  resources :tricks
  resources :guides
  resources :game_tricks

  namespace :admin do
    resources :series
    resources :categories
    resources :games
    resources :levels
    resources :resources
    resources :skips
    resources :tricks
    resources :guides
    resources :game_tricks
  end
end

app/views/admin/partials/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light style="background-color: #2596be
;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">SRT SR Wiki</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/admin">Dashboard</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Series', admin_series_index_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Games', admin_games_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', admin_categories_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Guides', admin_guides_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Tricks', admin_tricks_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Skips', admin_skips_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Levels', admin_levels_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Resources', admin_resources_path, class: 'nav-link' %>
        </li>
        </li>
      </ul>
    </div>
  </div>
</nav>